Import typeddict from typing_extentions
google/generative-ai-python pull request #104
Opened 2023-12-12 14:58 UTC by eavanvalkenburg

## Description of the change

When using classes from the types with Pydantic [as mentioned here],(https://docs.pydantic.dev/2.1/usage/types/dicts_mapping/#typeddict) Pydantic throws an error that typeddict needs to come from typing_extentions for python < 3.11, hence this PR.

## Motivation

Allows this packages classes to be used within pydantic based classes.

## Type of change
Choose one: Bug Fix

## Checklist

- [x] I have performed a self-review of my code.
- [x] I have added detailed comments to my code where applicable.
- [x] I have verified that my change does not break existing code.
- [x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [x] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

2023-12-12 23:34 UTC, markmcd commented
Do you have a link that explains why it's needed? The link you provided lists:

> This is a new feature of the Python standard library as of Python 3.8. Prior to Python 3.8, it requires the [typing-extensions](https://pypi.org/project/typing-extensions/) package. But required and optional fields are properly differentiated only since Python 3.9. We therefore recommend using [typing-extensions](https://pypi.org/project/typing-extensions/) with Python 3.8 as well.

We only support 3.9+, so it sounds like it's already OK, but that obviously isn't your experience so I'd like to understand the problem better.

2023-12-19 17:22 UTC, MarkDaoust requested changes
This looks pretty reasonable. 

The tests only pass because `typing_extensions` is indirectly pulled in by our `[dev]` install. 

Before we merge this, we need to add typing-extensions to the requirements in setup.py. 

Optional: use [environment markers](https://peps.python.org/pep-0508/#environment-markers) to make it a conditional requirement.

2023-12-20 00:44 UTC, MarkDaoust commented
To keep things simple is there any downside to always importing from typing-extensions?

I think I'm going to start with that.

2023-12-20 00:46 UTC, MarkDaoust approved these changes

2023-12-20 00:52 UTC, merged