fix: handle empty string in ChatSession.send_message
google/generative-ai-python pull request #134
Opened 2023-12-17 00:29 UTC by Hamza-nabil

## Description of the change

## Motivation

## Type of change
Choose one: (Bug fix | Feature request | Documentation | Other)

## Checklist

- [ X] I have performed a self-review of my code.
- [ X] I have added detailed comments to my code where applicable.
- [ X] I have verified that my change does not break existing code.
- [ X] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [ X] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

2023-12-18 16:55 UTC, MarkDaoust requested changes
That sounds right. I can't think of any cases where an empty `Content` would be valid. 
Could we move this to `content_types.to_content` so it applies everywhere?

2023-12-18 20:16 UTC, Hamza-nabil commented
Thank you for your feedback ! I've updated the code as suggested.

2023-12-19 16:52 UTC, MarkDaoust approved these changes
Thanks!

2023-12-19 17:01 UTC, MarkDaoust requested changes

2023-12-19 17:01 UTC, MarkDaoust commented on google/generativeai/types/content_types.py
> +        raise TypeError("content must not be empty")
```suggestion
        raise ValueError("content must not be empty")
```

2023-12-19 17:01 UTC, MarkDaoust approved these changes

2023-12-19 17:25 UTC, merged