Implement __repr__ for GenerateContentResponse and ChatSession
google/generative-ai-python pull request #202
Opened 2024-02-08 17:36 UTC by aidoskanapyanov

## Description of the change
Added a `__repr__` method to `GenerateContentResponse` and `ChatSession`. (WIP PR 🚧 for #173 )

## Motivation
Improve DX when debugging the code by being able to reproduce `response` and `chat` objects from the `repr` methods.

## Type of change
Feature request

## Checklist

- [x] I have performed a self-review of my code.
- [ ] I have added detailed comments to my code where applicable.
- [x] I have verified that my change does not break existing code.
- [x] My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
- [ ] I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
- [x] I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

2024-02-08 19:48 UTC, MarkDaoust requested changes
> remove stashing.

Yes. The response object already stashes so you don't need to. 
But I'm not sure exausting the iterator is the right thing to do here. 

1. `chunks` is the iterator's cache.
2. People expect __str__ not to edit the object, and they expect it to be idempotent. 

So showing what's left in the iterator doesn't feel right. 

IIUC, calling it twice `str(response); str(response)` will give two different responses. 
The first will show what was in the iterator, and copy it to the cache, and on the second call the iterator's exausted so it shows as [], right?

Maybe: 

if `_done`  show `self._result`
Otherwise show show `self.result, done=False, iterator=str(iterator)` to signal that iteration is incomplete?

Should we show that _error field if it's not None?

2024-02-08 19:49 UTC, MarkDaoust commented
@aidoskanapyanov @markmcd WDYT?

Also: Thanks for the PR!

2024-02-09 03:29 UTC, markmcd commented
> @markmcd WDYT?

Just a big +1 to Mark's comments about removing side-effects. And yes, `_error` too would be great, though keep the "internal" properties marked as internal (e.g. `_done`, `_error`), just to help clarify that users shouldn't be accessing those.

When you're ready, can you also add a few more test cases for responses in different states? e.g. a unary (non-streamed) response, a completed streaming response, a partial streaming response, and error cases.

And thanks!

2024-02-09 05:36 UTC, aidoskanapyanov commented
Yes, thanks! I was sort of aware that `repr` had a bug w/ side effects, before that tried to stash list_iterator's via `itertools.tee`, but it caused a lot failing tests 😅.

I just changed the code now it shouldn't case side-effect and returns something like this when `self._done == True`:
```python
response:                                                                                                                                                                                                                  
GenerateContentResponse(                                                                                                                                                                                                   
    done=True,                                                                                                                                                                                                             
    iterator=None,                                                                                                                                                                                                         
    result=glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'Hello world!'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]}),        
    chunks=iter([glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'Hello world!'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]})]) 
)                 
```

and when it's `False`:
```python
response:                                                                                                                                                                                                       
GenerateContentResponse(                                                                                                                                                                                        
    done=False,                                                                                                                                                                                                 
    iterator=<list_iterator>,                                                                                                                                                                                   
    result=glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'a'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]}),        
    chunks=iter([glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'a'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]})]) 
)
```

Also, it should append a `self._error` below if there is one, something like the following:
```python
response:
GenerateContentResponse(
    done=False,
    iterator=<list_iterator>,
    result=glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'a'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]}),
    chunks=iter([glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'a'}], 'role': ''}, 'finish_reason': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]})])
),
error=BlockedPromptException, candidates {
  content {
    parts {
      text: "a"
    }
  }
}
```

 I'll add some test cases to make sure the error appears correctlly, also for this too:
> When you're ready, can you also add a few more test cases for responses in different states? e.g. a unary (non-streamed) response, a completed streaming response, a partial streaming response, and error cases.

2024-02-09 12:14 UTC, aidoskanapyanov commented
I implemented a repr for `ChatSession` too. Do you also want to see `_last_received` or `_last_sent` in chat's repr output?

2024-02-13 21:22 UTC, MarkDaoust commented
Thank you! This is way better than what we've got now. 

There are a couple of tiny changes I'll make before merging. 

Give me a minute.

2024-02-13 23:38 UTC, MarkDaoust commented
I cleared the chunks from the GenerateContentResponse's __repr__ just for signal to noise raito. I see that you were trying to make  the output executable to return an identical object. It doesn't seem worth it.  

> I implemented a repr for `ChatSession` too. Do you also want to see `_last_received` or `_last_sent` in chat's repr output?

last_sent + last_received are so I can handle the status of in-progress streaming responses in chat, and throw errors if the stream is incomplete or broken. So I added `<STREAM IN PROGRESS>`  and `<STREAM ERROR>` placeholders to show that.

2024-02-13 23:40 UTC, MarkDaoust approved these changes

2024-02-14 17:03 UTC, MarkDaoust approved these changes

2024-02-14 17:22 UTC, merged