The send_message_async method should call the asynchronous method generate_content_async
google/generative-ai-python pull request #229
Opened 2024-03-07 09:17 UTC by xnny

## Description of the change
Now using the send_message_async method will cause an error ` object GenerateContentResponse can't be used in 'await' expression `

## Motivation
Running using an asynchronous method, just upgrading the library caused my entire project to not run properly

## Type of change
Bug fix 

## Checklist
-  I have performed a self-review of my code.
-  I have added detailed comments to my code where applicable.
-  I have verified that my change does not break existing code.
-  My PR is based on the latest changes of the main branch (if unsure, please run `git pull --rebase upstream main`).
-  I am familiar with the [Google Style Guide](https://google.github.io/styleguide/) for the language I have coded in.
-  I have read through the [Contributing Guide](https://github.com/google/generative-ai-python/blob/main/CONTRIBUTING.md) and signed the [Contributor License Agreement](https://cla.developers.google.com/about).

2024-03-07 16:04 UTC, MarkDaoust approved these changes

2024-03-07 16:04 UTC, MarkDaoust requested changes
Please sign the CLA so we can merge this.

2024-03-09 12:52 UTC, LindaLawton commented
@xnny  please sign the CLA so we can get this merged

2024-03-10 22:02 UTC, Nayjest commented
Hey everyone, is there any chance that this will be merged at some point?

Currently, Gemini via AI Studio is not supported in our software solely due to this bug. 
Additionally, Gemini on VertexAI has different issues, so Gemini models are completely unusable via official Google python cli libs for at the moment --> looks like we will release without Gemini support :'(

2024-03-11 11:09 UTC, Nayjest commented
@LindaLawton  @MarkDaoust, please see if you can merge the same changes from here: https://github.com/google/generative-ai-python/pull/235

@xnny, I'm really sorry for recreating your PR and appreciate the work you've done. I just need these changes in the main/PyPI as soon as possible 🙏

2024-03-11 16:15 UTC, merged

2024-03-11 16:17 UTC, MarkDaoust commented
Merged. I'll see if I can get a 0.4.1 release out today.

2024-03-11 16:18 UTC, Nayjest commented
Thanks!